name: Balena Push

on:
  workflow_dispatch:

jobs:
  balena-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Balena Push
        uses: bherbruck/balena-push-action@v0.2
        with:
          balena-api-key: ${{ secrets.BALENA_API_KEY }}
          balena-app-name: ${{ vars.BALENA_APP_NAME }}

