name: Balena Push

on:
  workflow_dispatch:

jobs:
  balena-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .github

    steps:
      - uses: actions/checkout@v3

      - name: Install balena-cli
        run: bash ./scripts/install-balena-cli.sh

      - name: Log in to balena
        run: balena login --token ${{ secrets.BALENA_API_KEY }}

      - name: Push code to balena
        run: balena push ${{ vars.BALENA_APP_NAME }}